import DeleteSlider from "../../pages/Slider/DeleteSlider";


export default {
login: "Auth/login",
register: "Auth/register",
createRole: "Auth/CreateRole",
AssignRole: "Auth/AssignRole",
UpdateUserRoles: "Auth/UpdateUserRoles",
GetUserRoles: "Auth/GetUserRoles",
GetUser:"Auth/GetUser",
GetAllUsers:"Auth/GetAllUsers",
GetAllRolse: "Auth/GetAllRolse",
DeleteRole: "Auth/DeleteRole",
DeActiveUser: "Auth/DeActiveUser",
ActiveUser: "Auth/ActiveUser",
CreateSlider: "/Slider/CreateWithFile",
UpdateSlider: "/Slider/UpdateWithFile",
DeleteSlider: "/Slider/Delete",
SliderList:"/Slider/List",
CreateSliderWithFile : "Slider/CreateWithFile",
UpdateSliderWithFile : "Slider/UpdateSliderWithFile",
GetSlider:"",
CreateBlogPost: "BlogPost/CreateWithFile",
BlogPostList: "BlogPost/List",
DeleteBlogPost: "BlogPost/Delete",
EditBlogPost: "BlogPost/UpdateWithFile",
CreateBlogCategories: "BlogCategories/Create",
BlogCategoriesList: "BlogCategories/List",
DeleteBlogCategories: "BlogCategories/Delete",
EditBlogCategories: "BlogCategories/UpdateWithFile",
CreateBlogComment: "BlogComment/CreateWithFile",
BlogCommentList: "BlogComment/List",
DeleteBlogComment: "BlogComment/Delete",
EditBlogComment: "BlogComment/UpdateWithFile",
CreateBlogPostTag: "BlogPostTag/CreateWithFile",
BlogPostTagList: "BlogPostTag/List",
DeleteBlogPostTag: "BlogPostTag/Delete",
EditBlogPostTag: "BlogPostTag/UpdateWithFile",
CreateBlogTag: "BlogTag/Create",
BlogTagList: "BlogTag/List",
DeleteBlogTag: "BlogTag/Delete",
EditBlogTag: "BlogTag/Update",
GetBlogTagById: "BlogTag/Get",

CarInspectionServiceList: "CarInspectionService/List",
CreateCarInspectionService: "CarInspectionService/CreateWithFile",
DeleteCarInspectionService: "CarInspectionService/Delete",
EditCarInspectionService: "CarInspectionService/UpdateWithFile",
GetCarInspectionServiceById: "CarInspectionService/Get",

secretOfOurServiceQualityList: "secretOfOurServiceQuality/List",
CreateSecretOfOurServiceQuality: "secretOfOurServiceQuality/CreateWithFile",
DeleteSecretOfOurServiceQuality: "secretOfOurServiceQuality/Delete",
EditSecretOfOurServiceQuality: "secretOfOurServiceQuality/UpdateWithFile",
GetSecretOfOurServiceQuality: "secretOfOurServiceQuality/Get",

CarBrandList: "CarBrand/List",
CreateCarBrand: "CarBrand/CreateWithFile",
DeleteCarBrand: "CarBrand/Delete",
EditCarBrand: "CarBrand/UpdateWithFile",
GetCarBrand: "CarBrand/Get",

CarGroupList: "CarGroup/List",
CreateCarGroup: "CarGroup/CreateWithFile",
DeleteCarGroup: "CarGroup/Delete",
EditCarGroup: "CarGroup/UpdateWithFile",
GetCarGroup: "CarGroup/Get",

CarInspectionList: "CarInspection/List",
CreateCarInspection: "CarInspection/CreateWithFile",
DeleteCarInspection: "CarInspection/Delete",
EditCarInspection: "CarInspection/UpdateWithFile",
GetCarInspection: "CarInspection/Get",

CarInspectionDateTypeList: "CarInspectionDateType/List",
CreateCarInspectionDateType: "CarInspectionDateType/CreateWithFile",
DeleteCarInspectionDateType: "CarInspectionDateType/Delete",
EditCarInspectionDateType: "CarInspectionDateType/UpdateWithFile",
GetCarInspectionDateType: "CarInspectionDateType/Get",

CarInspectionFeatureList: "CarInspectionFeatureType/List",
CreateCarInspectionFeature: "CarInspectionFeatureType/CreateWithFile",
DeleteCarInspectionFeature: "CarInspectionFeatureType/Delete",
EditCarInspectionFeature: "CarInspectionFeatureType/UpdateWithFile",
GetCarInspectionFeature: "CarInspectionFeatureType/Get",

CarInspectionLocationList: "CarInspectionLocationType/List",
CreateCarInspectionLocation: "CarInspectionLocationType/CreateWithFile",
DeleteCarInspectionLocation: "CarInspectionLocationType/Delete",
EditCarInspectionLocation: "CarInspectionLocationType/UpdateWithFile",
GetCarInspectionLocation: "CarInspectionLocationType/Get",

CarInspectionTypeList: "CarInspectionType/List",
CreateCarInspectionType: "CarInspectionType/Create",
DeleteCarInspectionType: "CarInspectionType/Delete",
EditCarInspectionType: "CarInspectionType/Update",
GetCarInspectionType: "CarInspectionType/Get",

DateAndTimeList: "DateAndTime/List",
CreateDateAndTime: "DateAndTime/CreateWithFile",
DeleteDateAndTime: "DateAndTime/Delete",
EditDateAndTime: "DateAndTime/UpdateWithFile",
GetDateAndTime: "DateAndTime/Get",

FlowLifeCycleList: "FlowLifeCycle/List",
CreateFlowLifeCycle: "FlowLifeCycle/CreateWithFile",
DeleteFlowLifeCycle: "FlowLifeCycle/Delete",
EditFlowLifeCycle: "FlowLifeCycle/UpdateWithFile",
GetFlowLifeCycle: "FlowLifeCycle/Get",

FlowStateList: "FlowState/List",
CreateFlowState: "FlowState/CreateWithFile",
DeleteFlowState: "FlowState/Delete",
EditFlowState: "FlowState/UpdateWithFile",
GetFlowState: "FlowState/Get",

FlowTypeList: "FlowType/List",
CreateFlowType: "FlowType/CreateWithFile",
DeleteFlowType: "FlowType/Delete",
EditFlowType: "FlowType/UpdateWithFile",
GetFlowType: "FlowType/Get",

MasterSiteDetailList: "MasterSiteDetail/List",
CreateMasterSiteDetail: "MasterSiteDetail/CreateWithFile",
DeleteMasterSiteDetail: "MasterSiteDetail/Delete",
EditMasterSiteDetail: "MasterSiteDetail/UpdateWithFile",
GetMasterSiteDetail: "MasterSiteDetail/Get",

WhyWeList: "WhyWe/List",
CreateWhyWe: "WhyWe/CreateWithFile",
DeleteWhyWe: "WhyWe/Delete",
EditWhyWe: "WhyWe/UpdateWithFile",
GetWhyWe: "WhyWe/Get",





} as { [type: string]: string };
